### PR TITLE
Point to newest docker image

### PR DESCRIPTION
**Pull request by SashaWeinstein**
Once this gets merged in I can publish a new version of the action and test the new image at https://hub.docker.com/layers/library/nycplanning/library/ubuntu-pluto_templates/images/sha256-baee6f9476111bdda586e729c5169e236b542975ea85333af8af75e12cfe87ee?context=repo

### CODE REVIEW

**Comment by SashaWeinstein** [comment]
The way I created the new image was to open up a data library dev container, saved it to an image with `docker commit`, and then upload it to docker hub

**Comment by td928** [comment]
So my understanding is that this image is already published on github. I guess the approval is contingent on whether the use of the image on the pluto side is successful or not?

**Comment by SashaWeinstein** [comment]
So the way it works in my understanding is that we can point to a particular version of the action. You can see that [pluto points to v1.1](https://github.com/NYCPlanning/db-pluto/blob/0f078657098c6172c28620fc5c8e3eb43d3bfc8d/.github/workflows/publish.yml#L43). 
So once this is merged we can publish this under a different branch and test a publishing action from pluto that uses this image

**Comment by td928** [comment]
> So the way it works in my understanding is that we can point to a particular version of the action. You can see that [pluto points to v1.1](https://github.com/NYCPlanning/db-pluto/blob/0f078657098c6172c28620fc5c8e3eb43d3bfc8d/.github/workflows/publish.yml#L43). So once this is merged we can publish this under a different branch and test a publishing action from pluto that uses this image

the different branch would be the main branch?

**Comment by SashaWeinstein** [comment]
Sorry that was unclear. We would test off the production branch until we got it to work, then merge it in

**Comment by SashaWeinstein** [comment]
This [blog post](https://stackoverflow.com/questions/70970561/install-gdal-on-poetry-project) was key to setting up deployed docker image under tag `ubuntu-pluto_templates`

**Comment by mbh329** [comment]
Is this ready to be reviewed?

**Comment by SashaWeinstein** [comment]
Good question, it is not. Won't have anything ready for review by the end of this week

**Comment by SashaWeinstein** [comment]
After working on this all day, I'm running [publishing actions](https://github.com/NYCPlanning/db-pluto/runs/8278219211?check_suite_focus=true) that successfully build but then throw this error: 
```  Poetry could not find a pyproject.toml file in /github/workspace or its parents```
I'm not sure what's happening, it seems that `script.py` in this repo is being run from a directory other than `/library'. Something I don't understand is happening under the hood, think it's time for us to look at this together

**Comment by SashaWeinstein** [comment]
Maybe poetry just isn't the right tool here. Or maybe we can install from poetry but not to a virtual environment and then use `CMD ["python", "script.py"]` without needing poetry

**Pull request closed without merging**
